version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: web-environments/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: web-environments/start_container.sh
      timeout: 300
      runas: root
